name: demo-awx-ee
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker build . --tag ghcr.io/elouloouu/demo-awx-ee:latest
          docker run ghcr.io/elouloouu/demo-awx-ee:latest
          docker push ghcr.io/elouloouu/demo-awx-ee:latest
